[package]
name = "learn-from-example-wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.16.1", features = ["derive"] }
glam = "0.28.0"
pollster = "0.3.0"
wgpu = "0.20.1"
winit = "0.30.3"
